blueprint:
  name: Fan Control 
  description: Turn off fan after a specified delay.
  domain: automation
  input:
    exhaust_fan:
      name: Bathroom Exhaust Fan
      description: The fan to control.
      selector:
        entity:
          domain: switch
    delay_time:
      name: Delay Time
      description: Time in seconds to wait before turning off the bathroom fan.
      default: 600
      selector:
        number:
          min: 0
          max: 3600
          step: 1
    automation_lock:
      name: Automation Lock
      description: A boolean (input_boolean) helper that prevents this automation from running when turned on (e.g., when triggered by another automation). Leave empty to disable this check.
      default: []
      selector:
        entity:
          domain: input_boolean
triggers:
  - trigger: state
    entity_id: !input exhaust_fan
    to: "on"
variables:
  automation_lock: !input automation_lock
conditions:
  - condition: template
    value_template: "{{ not automation_lock or is_state(automation_lock, 'off') }}"
actions:
  - delay:
      seconds: !input delay_time
  - service: switch.turn_off
    target:
      entity_id: !input exhaust_fan